### ISSUE TITLE
Eating doesn't fill up the hunger bar

### ISSUE THREAD

**Issue by Denisgri109** [IzzelAliz/Arclight#1428]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT

### OS & Java versions

OS: Windows 11 x64, java version "21.0.3" 2024-04-16 LTS

### Plugins and Mods

```raw
i didnt install any plugins/mods
```

### Description

When ever i run the minecraft server with arclight 1.21 version and i need to fill up my hunger bar, and i eat, the amount of food gets lower but it doesnt fill up my hunger bar at all. i can eat 50-60 and yet the hunger bar is still the same as it was.

**Comment by 7Wdev** [comment]
yea I am facing this exact issue

**Comment by Stormcruzerlore** [comment]
can confrim same issue not generating any   errors in the server consol or anything in the logs either

**Comment by troopaofficial** [comment]
+1 for me aswell, first time running arclight, no mods or plugins even added yet however the world is imported

**Comment by REDKING-11** [comment]
same here

**Comment by qyl27** [comment]
Fixed, refer #1469

**Comment by troopaofficial** [comment]
This is not fixed, installing a mod to remove the hunger bar is not fixing the problem?

Unless I’m missing something from that thread?

**Comment by qyl27** [comment]
> This is not fixed, installing a mod to remove the hunger bar is not fixing the problem?
> 
> Unless I’m missing something from that thread?

#1469 was closed by a commit, but not the remove hunger bar advice, the line `qyl27 closed this as completed in 2f61580 [2 days ago]` means the builds after 2f61580 were fixed.  
Btw, I didn't think removing the hunger bar was a resolution :(

**Comment by troopaofficial** [comment]
Oh Jesus, my apologies lol

**Comment by Captainpax** [comment]
> > This is not fixed, installing a mod to remove the hunger bar is not fixing the problem?
> > Unless I’m missing something from that thread?
> 
> #1469 was closed by a commit, but not the remove hunger bar advice, the line `qyl27 closed this as completed in 2f61580 [2 days ago]` means the builds after [2f61580](https://github.com/IzzelAliz/Arclight/commit/2f615809f2913f08641edcb13aa4133064011535) were fixed. Btw, I didn't think removing the hunger bar was a resolution :(

So you fixed it but didn't post the update? I just downloaded Arclight and still have the same problem.
