### ISSUE TITLE
Player Kick, Ban, Tempban does not work

### ISSUE THREAD

**Issue by Yujichan23** [IzzelAliz/Arclight#1540]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Neoforge arclight-1.21.1-1.0.0-SNAPSHOT-0d31387

### OS & Java versions

21.0.5

### Plugins and Mods

```raw
[02:29:20 INFO] [Console]: Plugins (2): Essentials, AuthMe
```

### Description

Authme

when a player enters a wrong password, the server should kick the player out off the server

EssentialsX

Kick, Ban & Tempban command should Kick, Ban or Tempban a Player

### Step to reproduce

AuthMeReloaded

1. Install AuthMe
2. Join the game
3. Register
4. Leave the game
5. Login with wrong password

EssentialsX

1. Install EssentialsX
2. Join the server
3. /kick [Player], /ban [Player], /tempban [Player] [Duration]

### Logs

[latest.log](https://github.com/user-attachments/files/17654975/latest.log)

**Comment by Yujichan23** [comment]
@qyl27 quick question is the bug fixed, and when will this patch be applied?

**Comment by qyl27** [comment]
> @qyl27 quick question is the bug fixed, and when will this patch be applied?

Yes, It was fixed in c3818c5 yesterday, this message is in the 3 lines above your comment.  
You can download the newest build in our actions page.

**Comment by Yujichan23** [comment]
@qyl27 I've Downloaded the build [c3818c5](https://github.com/IzzelAliz/Arclight/commit/c3818c5f6b83ff3e1d7065aa8d775516043ce62a) , reinstalled the plugins, and run the server, the bug and error still persist

Here is the latest logs:
[latest.log](https://github.com/user-attachments/files/17672124/latest.log)

Error
java.lang.AbstractMethodError: Receiver class net.minecraft.server.network.ServerGamePacketListenerImpl does not define or inherit an implementation of the resolved method 'abstract void kickPlayer(net.minecraft.network.chat.Component)' of interface org.bukkit.craftbukkit.v1_21_R1.entity.CraftPlayer$TransferCookieConnection.

**Comment by qyl27** [comment]
I have committed another fix, sorry for my mistake.

**Comment by AgentMelinda** [comment]
@qyl27 thank you for your work! <3 much love

**Comment by Yujichan23** [comment]
@qyl27 it is now working as intended thanks..

Just to notify, a warning from the console:
[13:16:25 WARN]: handleDisconnection() called twice

also i've found another bug and error on the latest build a4fc8e0. I've isolated it with spaces so that it is easier to find.

Here is the latest log:
[latest.log](https://github.com/user-attachments/files/17678972/latest.log)

after a player is unbanned for Ban or Tempban. On first Join it throws a warning then an error, but on the second attempt it proceeds to enter the game as if its normal.

I might as well report this since it is related.

**Comment by Yujichan23** [comment]
@qyl27 All intended features are now working properly upon testing. Thanks for the good work.
